### ISSUE TITLE
Implement Logging for Console Application

### ISSUE THREAD

**Issue by aherd2985** [aherd2985/UtilityBelt#13]
An example would be NLog:
https://nlog-project.org/

Flexible & free open-source logging for .NET

**Comment by mimam419** [comment]
Hello @aherd2985,

Is this still open?
If yes, can you assign it to me?

**Comment by aherd2985** [comment]
Yes it is, I have it assigned over to you.

Please grab the latest and feel free to let me know if you run into any issues or have any questions.

It has been very active the last 24 hours, thank you for your time and help!

**Comment by PBWim** [comment]
@aherd2985 : 
I have added a pull request (#64 ) to log the files. 
Please review the pull request and provide feedback. 
Thank you...

**Comment by Huray-hub** [comment]
Hello! Is this still open? Can u assign it to me?
