### ISSUE TITLE
C# Models are camelCase which are against the official Pascal Case naming convention

### ISSUE THREAD

**Issue by hariharansubramanian** [aherd2985/UtilityBelt#28]
The C# Model classes use camelCase properties to mimic the JSON object.
This violates the Pascal case naming convention for class objects used in C# programs.

@aherd2985 would you accept a Pull request fixing this?

**Comment by aherd2985** [comment]
Sure, please grab the latest to minimize conflict/merge issues, thank you!

**Comment by aherd2985** [comment]
Merge completed, thank you!
