### ISSUE TITLE
Ghost Game needs to limit User choice

### ISSUE THREAD

**Issue by aherd2985** [aherd2985/UtilityBelt#55]
Option 24 "Fun Ghost Game"

Need to parse the user input and restrict the user to only selecting a 1,2, or 3.

Else, have them retry and continue playing the game.

**Comment by CES112** [comment]
@aherd2985 Can I be assigned to this?

**Comment by aherd2985** [comment]
Take it over!

**Comment by CES112** [comment]
@aherd2985 Attaching pull request. #59
