### ISSUE TITLE
Add fun functionalities to execute in a Console Application

### ISSUE THREAD

**Issue by aherd2985** [aherd2985/UtilityBelt#7]
Happy coding!

**Comment by AyushRajSharma** [comment]
hi, i am Ayush Raj, 
i am beginner and want to contribute, can you please explain what type of functionality you are wondering.
please assign me.

**Comment by aherd2985** [comment]
Any fun idea you have, feel free to be as creative as you'd like.

You could display ascii art, interact with an api or chat bot, automate sending a message, etc.

I am trying to provide an open space for anyone to practice/contribute!

**Comment by aherd2985** [comment]
If you can't decide on something new, you could add a way for the user to loop back to the Menu Options to try something else.

I also hadn't added any logging or send a notification by email if it crashes.

Does that help?

**Comment by AyushRajSharma** [comment]
[added ascii art](https://github.com/aherd2985/UtilityBelt/pull/9#issue-497342477)

**Comment by AyushRajSharma** [comment]
@aherd2985  please add tag orbtoberfest too
