### ISSUE TITLE
🍻 🎃 👻  Error handling and null checks  👻 🎃 🍻  

### ISSUE THREAD

**Issue by 1RedOne** [aherd2985/UtilityBelt#76]
Noticed some spots which could throw if a web request fails, mind if I add a few null checks, try catch and unit tests around them?  I'll keep the PRs small.  🍻 🎃 👻

**Comment by aherd2985** [comment]
Sounds great, thank you so much for your time and help!

**Comment by 1RedOne** [comment]
Happy to help, this is a cool project and I've been doing a lot of this stuff in a recent project.  It's strangely zen.

Resolved in #79
