### ISSUE TITLE
👻👾Unit Tests for Kanye Quotes👾👻

### ISSUE THREAD

**Issue by 1RedOne** [aherd2985/UtilityBelt#82]
Being yeezey ain't easy

The Yeezus needs some error handling, some null-checks, some “Whoop-de-di scoop, whoop poop", and to migrate to SystemWebClient for ez testing.

I'mma let you finish but this is about to be the greatest pull request of all time

**Comment by aherd2985** [comment]
Hahahaha, sounds great! 

Thank you!
